version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    # For development, you might want to use this instead:
    # command: npm run dev
    # ports:
    #   - "5173:5173" 